version: '3'
services:
    freelara-nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/app
            - ./docker/nginx/ssl:/etc/nginx/ssl
        depends_on:
            - freelara-php-fpm
        ports:
            - "8080:443"
    freelara-php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./:/app
        depends_on:
            - freelara-mysql
    freelara-php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        depends_on:
            - freelara-mysql
        tty: true
    freelara-mysql:
        image: mysql:5.7
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "33062:3306"
    freelara-node-watch:
        image: node:12.7-alpine
        volumes:
            - ./:/app
        working_dir: /app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
    freelara-node:
        image: node:12.7-alpine
        volumes:
            - ./:/app
        working_dir: /app


volumes:
    freelara-mysql:
    composer: